controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

#landing:
#    path: /start
#    controller: App\Controller\DefaultController::root
#
#add new record:
#    path: /newbook
#    controller: App\Controller\DefaultController::addNewBook
